server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: product-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: product-service
          service: product-service
          __path__: /var/log/app/*.log
    pipeline_stages:
      - match:
          selector: '{job="product-service"}'
          stages:
            - regex:
                expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3})\s+(?P<level>\w+)\s+(?P<logger>\S+)\s+:\s+(?P<message>.*)$'
            - labels:
                level:
                logger:
            - timestamp:
                source: timestamp
                format: '2006-01-02 15:04:05.000'
